language: java
jdk:
  - openjdk11

# Instalar dependencias
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

# Ejecutar las pruebas y generar el informe de cobertura
script:
  - mvn test jacoco:report

# Después de ejecutar las pruebas, enviar los resultados de cobertura a Code Climate
after_success:
  - pip install codeclimate-test-reporter
  - codeclimate-test-reporter --file target/site/jacoco/jacoco.xml --language java
