name: Codacy and Jacoco Coverage Reporter

on:
  push:
    branches:
      - main

jobs:
  codacy-and-jacoco-coverage-reporter:
    runs-on: ubuntu-latest
    name: Codacy and Jacoco Coverage Reporter
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 1.8

      - name: Build with Ant
        run: ant -noinput -buildfile build.xml

      - name: Test with Ant
        run: ant -buildfile build.xml test

      - name: Generate Jacoco coverage report
        run: ant -buildfile build.xml jacoco-report

      - name: Run Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./report.xml
